Repository openshift/federation-dev, pull requests merged in 2019-10, with the labels that each got.

#128 Added feedback from EMEA RHTE
  labs/3.md
  labs/instructor-kickoff.md
Labels: size/M

#130 Added warning/tip images to lab comments
  labs/10.md
  labs/2.md
  labs/3.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/assets/tip-icon.png
  labs/assets/warning-icon.png
Labels: size/M

#131 Added manifests for GitOps Katacoda scenarios
  gitops-introduction/gogs/gogs-persistent-template.yaml
  gitops-introduction/simple-app/reversewords_app/deployment.yaml
  gitops-introduction/simple-app/reversewords_app/namespace.yaml
  gitops-introduction/simple-app/reversewords_app/service.yaml
Labels: size/L

#129 Kustomize ready Pacman
  gitops/README.md
  gitops/haproxy.txt
  gitops/pacman/base/kustomization.yaml
  gitops/pacman/base/mongodb-users-secret.yaml
  gitops/pacman/base/namespace.yaml
  gitops/pacman/base/pacman-deployment.yaml
  gitops/pacman/base/pacman-service.yaml
  gitops/pacman/base/pacman-serviceaccount.yaml
  gitops/pacman/base/skuppman-clusterrole.yaml
  gitops/pacman/base/skuppman-clusterrolebinding.yaml
  gitops/pacman/base/skuppman-route.yaml
  gitops/pacman/overlays/east1/haproxy-configmap.yaml
  gitops/pacman/overlays/east1/haproxy-deployment.yaml
  gitops/pacman/overlays/east1/haproxy-service.yaml
  gitops/pacman/overlays/east1/kustomization.yaml
Labels: size/L

#133 Update pacman-route.yaml
  labs/lab-7-assets/base/pacman-route.yaml
Labels: size/XS

#132 Auto demo gitops
  automated-demo-gitops/.gitignore
  automated-demo-gitops/README.md
  automated-demo-gitops/auto-demo.sh
  automated-demo-gitops/bin/.gitignore
  automated-demo-gitops/demo-script.md
  automated-demo-gitops/inventory.json.tmpl
  automated-demo-gitops/ssl/.gitignore
  automated-demo-gitops/ssl/ca-config.json
  automated-demo-gitops/ssl/ca-csr.json
  automated-demo-gitops/ssl/mongodb-csr.json
  automated-demo-gitops/yaml-resources/argocd/.gitignore
  automated-demo-gitops/yaml-resources/argocd/argocd-install.yaml
  automated-demo-gitops/yaml-resources/gogs/.gitignore
  automated-demo-gitops/yaml-resources/gogs/gogs.yaml
  automated-demo-gitops/yaml-resources/gogs/postgres.yaml
  automated-demo-gitops/yaml-resources/haproxy/.gitignore
  automated-demo-gitops/yaml-resources/haproxy/haproxy-clusterip-service.yaml
  automated-demo-gitops/yaml-resources/haproxy/haproxy-deployment.yaml
  automated-demo-gitops/yaml-resources/haproxy/haproxy.tmpl
  automated-demo-gitops/yaml-resources/mongo/base/.gitignore
  automated-demo-gitops/yaml-resources/mongo/base/kustomization.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-namespace.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-pvc.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-route.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-rs-deployment.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-secret.yaml
  automated-demo-gitops/yaml-resources/mongo/base/mongo-service.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster1/.gitignore
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster1/kustomization.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster1/mongo-route.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster2/.gitignore
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster2/kustomization.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster2/mongo-route.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster3/.gitignore
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster3/kustomization.yaml
  automated-demo-gitops/yaml-resources/mongo/overlays/cluster3/mongo-route.yaml
  automated-demo-gitops/yaml-resources/pacman/base/.gitignore
  automated-demo-gitops/yaml-resources/pacman/base/kustomization.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-cluster-role-binding.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-cluster-role.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-deployment.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-namespace.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-route.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-secret.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-service-account.yaml
  automated-demo-gitops/yaml-resources/pacman/base/pacman-service.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster1/.gitignore
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster1/kustomization.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster1/pacman-deployment.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster2/.gitignore
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster2/kustomization.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster2/pacman-deployment.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster3/.gitignore
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster3/kustomization.yaml
  automated-demo-gitops/yaml-resources/pacman/overlays/cluster3/pacman-deployment.yaml
Labels: size/XXL
