Repository openshift/federation-dev, pull requests merged in 2019-07, with the labels that each got.

#19 Updated demo to use kubefed-operator v0.1.0
  automated-demo/auto-demo.sh
  automated-demo/yaml-resources/kubefed-operator/01-catalog-source-config.yaml
  automated-demo/yaml-resources/kubefed-operator/03-federation-subscription.yaml
  automated-demo/yaml-resources/mongo/01-mongo-federated-secret.yaml
  automated-demo/yaml-resources/mongo/02-mongo-federated-service.yaml
  automated-demo/yaml-resources/mongo/03-mongo-federated-pvc.yaml
  automated-demo/yaml-resources/mongo/04-mongo-federated-deployment-rs.yaml
  automated-demo/yaml-resources/olm/.gitignore
  automated-demo/yaml-resources/olm/01-olm.yaml
  automated-demo/yaml-resources/olm/02-olm.yaml
  automated-demo/yaml-resources/olm/03-subscription.yaml
  automated-demo/yaml-resources/pacman/01-mongo-federated-secret.yaml
  automated-demo/yaml-resources/pacman/02-pacman-federated-service.yaml
  automated-demo/yaml-resources/pacman/03-pacman-federated-ingress.yaml
  automated-demo/yaml-resources/pacman/04-pacman-federated-deployment-rs.yaml
Labels: size/XXL

#20 Workinprogress
  README-cdk.md
  README-minishift.md
  README-ocp4.md
  README.md
Labels: size/S

#22 Small fix autodemo
  automated-demo/yaml-resources/kubefed-operator/.gitignore
  automated-demo/yaml-resources/kubefed-operator/04-kubefed-resource.yaml
Labels: size/XS

#21 initial commit of modified / cleaned up lab
  README-labs.md
  README-ocp4.md
  README.md
  labs/1.md
  labs/10.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
Labels: size/XL

#28 removing extra "federation deployment" text
  labs/1.md
Labels: size/XS

#30 adding conclusion section
  labs/9.md
Labels: size/XS

#31 adding placeholder for admin notes
  labs/admin-guide
Labels: size/XS

#32 adding navigation for the pages
  labs/1.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
Labels: size/M

#33 organization to resolve #29
  README.md
  labs/README.md
Labels: size/M

#36 Small updates
  labs/2.md
  labs/3.md
Labels: size/L

#35 adding introduction chapter and fixing navigation
  labs/1.md
  labs/README.md
  labs/intro.md
Labels: size/L

#34 fixing broken links
  labs/README.md
Labels: size/S

#26 Rewrite pacman
  automated-demo/auto-demo.sh
  automated-demo/deploy-haproxy.md
  automated-demo/yaml-resources/kubefed-operator/04-kubefed-resource.yaml
  automated-demo/yaml-resources/pacman/.gitignore
  automated-demo/yaml-resources/pacman/04-pacman-federated-service-account.yaml
  automated-demo/yaml-resources/pacman/05-pacman-federated-cluster-role.yaml
  automated-demo/yaml-resources/pacman/06-pacman-federated-cluster-role-binding.yaml
  automated-demo/yaml-resources/pacman/07-pacman-federated-deployment-rs.yaml
  federated-mongodb/01-mongo-federated-secret.yaml
  federated-mongodb/02-mongo-federated-service.yaml
  federated-mongodb/03-mongo-federated-pvc.yaml
  federated-mongodb/04-mongo-federated-deployment-rs.yaml
  federated-mongodb/README.md
  federated-mongodb/mongo-yaml
  federated-pacman/01-haproxy
  federated-pacman/01-mongo-federated-secret.yaml
  federated-pacman/02-haproxy-service.yaml
  federated-pacman/02-pacman-federated-service.yaml
  federated-pacman/03-haproxy-deployment.yaml
  federated-pacman/03-pacman-federated-ingress.yaml
  federated-pacman/04-pacman-federated-deployment-rs.yaml
  federated-pacman/README.md
  federated-pacman/haproxy-yaml
  federated-pacman/pacman-yaml
  images/cluster-subscribe.png
  images/federation.png
  images/install.png
  images/kubefed.png
  images/subscribe.png
Labels: size/XL

#37 first run at rewrite
  labs/1.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/README.md
  labs/mongo-yaml
  labs/pacman-yaml
Labels: size/XL

#38 namespace change
  federated-pacman/README.md
Labels: size/XS

#39 fixing navigation links
  labs/README.md
Labels: size/S

#41 scollier intial review of lab1
  labs/1.md
Labels: size/S

#43 scolliers initial review of lab 2
  labs/2.md
Labels: size/S

#44 Updated auto-demo to use a fixed csv version
  automated-demo/auto-demo.sh
  automated-demo/yaml-resources/kubefed-operator/03-federation-subscription.yaml
  automated-demo/yaml-resources/olm/03-subscription.yaml
Labels: size/M

#46 Image
  automated-demo/yaml-resources/pacman/07-pacman-federated-deployment-rs.yaml
Labels: size/XS

#45 Mario's updates
  labs/1.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/8.md
Labels: size/L

#50 Minor lab corrections
  labs/3.md
Labels: size/XS

#54 fixes of issues
  labs/3.md
  labs/5.md
  labs/6.md
  labs/7.md
Labels: size/S

#55 Combined MongoDB steps into a single Lab
  labs/1.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
Labels: size/XL

#57 adding a bit more cluster context validation for users who may not be…
  labs/2.md
Labels: size/S

#56 adding the intro section to the main toc
  labs/README.md
Labels: size/XS

#59 fixes#51
  labs/5.md
  labs/6.md
Labels: size/S

#60 Workaround for https://github.com/openshift/kubefed-operator/issues/49
  README-ocp4.md
Labels: size/S

#62 Added placement modification use case
  labs/7.md
Labels: size/M

#67 Small fixes labs 3-5
  labs/3.md
  labs/5.md
Labels: size/L

#68 Added architecture details for mongo and pacman
  labs/5.md
  labs/6.md
  labs/assets/demo-arch.png
  labs/assets/federated-mongo-arch.png
Labels: size/S

#69 BYO Infrastructure added
  labs/6.md
  labs/byo-infrastructure.md
  labs/haproxy-yaml
Labels: size/L
