Repository openshift/federation-dev, pull requests merged in 2019-08, with the labels that each got.

#61 Scheduling
  labs/10.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
  labs/reverse-yaml/01-service.yaml
  labs/reverse-yaml/02-deployment.yaml
  labs/scheduling-yaml/basic-scheduling.yaml
  labs/scheduling-yaml/min-max-scheduling.yaml
  labs/scheduling-yaml/no-more-than-twenty.yaml
  labs/scheduling-yaml/rebalance.yaml
  labs/scheduling-yaml/weighted-scheduling.yaml
Labels: size/L

#74 Updated Labs to use latest rhte lab
  labs/1.md
  labs/10.md
  labs/11.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
  labs/assets/lab-env-overview.png
  labs/assets/request-env-gg.png
  labs/assets/ssh-details-gg.png
  labs/byo-infrastructure.md
  labs/intro.md
Labels: size/XL

#76 Add context to create commands
  labs/6.md
Labels: size/S

#77 error on cluster names
  labs/scheduling-yaml/weighted-scheduling.yaml
Labels: size/XS

#78 Minor updates
  labs/1.md
  labs/11.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
  labs/assets/api-endpoints.png
  labs/cleanup-instructions.md
  labs/intro.md
Labels: size/L

#80 adding link to operatorhub page
  labs/3.md
Labels: size/XS

#79 WIP: Pep's feedback
  automated-demo/yaml-resources/mongo/04-mongo-federated-deployment-rs.yaml
  labs/1.md
  labs/10.md
  labs/11.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
  labs/assets/federated-mongo-arch.png
  labs/assets/request-env-gg.png
  labs/intro.md
Labels: do-not-merge/work-in-progress, size/XL

#83 small fix
  labs/5.md
Labels: size/XS

#89 Small consistency changes
  labs/5.md
  labs/6.md
  labs/8.md
Labels: size/S

#90 Auto demo updates
  automated-demo/README.md
  automated-demo/auto-demo.sh
  automated-demo/deploy-haproxy.md
  automated-demo/inventory.json.tmpl
  automated-demo/yaml-resources/haproxy/haproxy-deployment.yaml
  automated-demo/yaml-resources/haproxy/haproxy.tmpl
Labels: size/L

#92 Updated byo instructions
  labs/byo-infrastructure.md
Labels: size/L

#91 Changed route creation
  labs/6.md
Labels: size/S

#88 WIP: HAproxy write-up
  labs/assets/ocp-router-1.gif
  labs/haproxy-tech-details.md
Labels: do-not-merge/work-in-progress, size/L

#94 Argocd
  labs/1.md
  labs/10.md
  labs/11.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
  labs/README.md
  labs/lab-4-assets/deployment.yaml
  labs/lab-4-assets/namespace.yaml
  labs/lab-4-assets/service.yaml
  labs/lab-5-assets/base/configMap.yaml
  labs/lab-5-assets/base/deployment.yaml
  labs/lab-5-assets/base/kustomization.yaml
  labs/lab-5-assets/base/namespace.yaml
  labs/lab-5-assets/base/service.yaml
  labs/lab-5-assets/overlay-assets/base/configMap.yaml
  labs/lab-5-assets/overlay-assets/base/deployment.yaml
  labs/lab-5-assets/overlay-assets/base/kustomization.yaml
  labs/lab-5-assets/overlay-assets/base/namespace.yaml
  labs/lab-5-assets/overlay-assets/base/service.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/deployment.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/map.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/deployment.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/map.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/deployment.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/map.yaml
  labs/lab-6-assets/01-mongo-secret.yaml
  labs/lab-6-assets/02-mongo-service.yaml
  labs/lab-6-assets/03-mongo-pvc.yaml
  labs/lab-6-assets/04-mongo-deployment-rs.yaml
  labs/lab-6-assets/namespace.yaml
  labs/lab-7-assets/base/00-pacman-namespace.yaml
  labs/lab-7-assets/base/01-pacman-secret.yaml
  labs/lab-7-assets/base/02-pacman-service.yaml
  labs/lab-7-assets/base/03-pacman-ingress.yaml
  labs/lab-7-assets/base/04-pacman-service-account.yaml
  labs/lab-7-assets/base/05-pacman-cluster-role.yaml
  labs/lab-7-assets/base/06-pacman-cluster-role-binding.yaml
  labs/lab-7-assets/base/07-pacman-deployment-rs.yaml
  labs/lab-7-assets/base/kustomization.yaml
  labs/lab-7-assets/overlays/cluster1/deployment.yaml
  labs/lab-7-assets/overlays/cluster1/kustomization.yaml
  labs/lab-7-assets/overlays/cluster2/kustomization.yaml
  labs/lab-7-assets/overlays/cluster3/kustomization.yaml
  labs/mongo-yaml
  labs/pacman-yaml
  labs/reverse-yaml/02-deployment.yaml
  labs/scheduling-yaml/basic-scheduling.yaml
  labs/scheduling-yaml/min-max-scheduling.yaml
  labs/scheduling-yaml/no-more-than-twenty.yaml
  labs/scheduling-yaml/rebalance.yaml
  labs/scheduling-yaml/weighted-scheduling.yaml
Labels: size/XXL

#96 add namespace values
  labs/lab-10-assets/pacman-application.yaml
  labs/lab-5-assets/base/configMap.yaml
  labs/lab-5-assets/base/deployment.yaml
  labs/lab-5-assets/base/service.yaml
Labels: size/XS

#104 Pacman now uses a OCP Route instead of ingress
  labs/7.md
  labs/lab-7-assets/base/kustomization.yaml
  labs/lab-7-assets/base/pacman-ingress.yaml
  labs/lab-7-assets/base/pacman-route.yaml
Labels: size/M

#105 Lab8 rewording
  labs/8.md
Labels: size/S

#106 Lab5 update
  labs/5.md
  labs/lab-5-assets/base/configmap.yaml
  labs/lab-5-assets/base/deployment.yaml
  labs/lab-5-assets/base/kustomization.yaml
  labs/lab-5-assets/base/namespace.yaml
  labs/lab-5-assets/base/route.yaml
  labs/lab-5-assets/base/service.yaml
  labs/lab-5-assets/overlay-assets/base/configmap.yaml
  labs/lab-5-assets/overlay-assets/base/kustomization.yaml
  labs/lab-5-assets/overlay-assets/base/namespace.yaml
  labs/lab-5-assets/overlay-assets/base/route.yaml
  labs/lab-5-assets/overlay-assets/base/service.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/configmap.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster1/route.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/configmap.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster2/route.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/configmap.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/kustomization.yaml
  labs/lab-5-assets/overlay-assets/overlays/cluster3/route.yaml
Labels: size/L

#107 s/clientvm/bastionvm/
  labs/1.md
  labs/assets/ssh-details-gg.png
Labels: size/S

#108 Added sync commands
  labs/8.md
Labels: size/XS

#109 Added verify-context script
  labs/2.md
  labs/README.md
Labels: size/S

#110 Fix lab9
  labs/9.md
Labels: size/S

#111 added in comment lines on multiple line items
  labs/10.md
  labs/2.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/8.md
  labs/9.md
Labels: size/L

#113 Minor updates
  labs/5.md
  labs/byo-infrastructure.md
  labs/cleanup-instructions.md
Labels: size/L

#114 clarity on the copy
  labs/9.md
Labels: size/XS
