Repository openshift/federation-dev, pull requests merged in 2019-09, with the labels that each got.

#117 official link
  labs/intro.md
Labels: size/XS

#116 Various updates to the RHTE lab
  labs/10.md
  labs/11.md
  labs/3.md
  labs/4.md
  labs/5.md
Labels: size/S

#118 Fixed oc get application
  labs/10.md
Labels: size/XS

#120 fixed lab5 formatting
  labs/5.md
Labels: size/S

#119 Added utility scripts to the lab repo
  labs/byo-infrastructure.md
  labs/utility/argocd-add-clusters
  labs/utility/gen-mongo-certs
  labs/utility/namespace-cleanup
  labs/utility/verify-contexts
  labs/utility/wait-for-argo-app
  labs/utility/wait-for-deployment
  labs/utility/wait-for-mongo-replicaset
Labels: size/L

#122 removal of the command showing how to manually log in
  labs/3.md
Labels: size/S

#123 Added workaround commands
  labs/10.md
Labels: size/S

#125 Splitting long commands for readability
  labs/10.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
  labs/7.md
  labs/9.md
Labels: size/L
