Repository openshift/federation-dev, pull requests merged in 2019-05, with the labels that each got.

#11 Rewrite of the README
  README.md
Labels: size/S

#16 Added automated pacman+mongo demo
  automated-demo/.gitignore
  automated-demo/README.md
  automated-demo/auto-demo.sh
  automated-demo/bin/.gitignore
  automated-demo/demo-script.md
  automated-demo/deploy-haproxy.md
  automated-demo/inventory.json.tmpl
  automated-demo/ssl/.gitignore
  automated-demo/ssl/ca-config.json
  automated-demo/ssl/ca-csr.json
  automated-demo/ssl/mongodb-csr.json
  automated-demo/yaml-resources/haproxy/.gitignore
  automated-demo/yaml-resources/haproxy/haproxy-deployment.yaml
  automated-demo/yaml-resources/haproxy/haproxy-service.yaml
  automated-demo/yaml-resources/haproxy/haproxy.tmpl
  automated-demo/yaml-resources/kubefed-operator/.gitignore
  automated-demo/yaml-resources/kubefed-operator/01-catalog-source-config.yaml
  automated-demo/yaml-resources/kubefed-operator/02-federation-operator-group.yaml
  automated-demo/yaml-resources/kubefed-operator/03-federation-subscription.yaml
  automated-demo/yaml-resources/mongo/.gitignore
  automated-demo/yaml-resources/mongo/01-mongo-federated-secret.yaml
  automated-demo/yaml-resources/mongo/02-mongo-federated-service.yaml
  automated-demo/yaml-resources/mongo/03-mongo-federated-pvc.yaml
  automated-demo/yaml-resources/mongo/04-mongo-federated-deployment-rs.yaml
  automated-demo/yaml-resources/pacman/.gitignore
  automated-demo/yaml-resources/pacman/01-mongo-federated-secret.yaml
  automated-demo/yaml-resources/pacman/02-pacman-federated-service.yaml
  automated-demo/yaml-resources/pacman/03-pacman-federated-ingress.yaml
  automated-demo/yaml-resources/pacman/04-pacman-federated-deployment-rs.yaml
  images/federated-mongo-diagram.png
  images/pacman-app-diagram.png
Labels: size/XXL

#17 minor grammatical fixes
  README.md
Labels: size/S

#18 Updated autodemo to make it work with OCP3 and OCP4
  automated-demo/README.md
  automated-demo/auto-demo.sh
  automated-demo/inventory.json.tmpl
Labels: size/M
