Repository openshift/federation-dev, pull requests merged in 2020-01, with the labels that each got.

#138 removing references to tech exchange and making more generic
  README.md
  labs/3.md
  labs/README.md
  labs/byo-infrastructure.md
Labels: size/S

#139 fixing argocd version
  labs/1.md
Labels: size/S

#143 removing reference to rhte
  labs/4.md
Labels: size/S

#145 fixing some typos in lab 5
  labs/5.md
Labels: size/XS

#151 fixing image location
  labs/9.md
Labels: size/XS

#153 Fixed intro
  labs/2.md
  labs/assets/request-env-gg.png
  labs/intro.md
Labels: size/S

#159 Fixed ssh screenshot and added useful resources
  labs/11.md
  labs/assets/ssh-details-gg.png
Labels: size/S

#155 adding blogs
  labs/11.md
Labels: size/XS

#160 Added Andy's suggestions
  labs/10.md
  labs/6.md
  labs/9.md
Labels: size/XS

#161 fixing a small typo
  labs/4.md
Labels: size/XS

#162 Included feedback from DevConf.cz
  labs/10.md
  labs/3.md
  labs/4.md
  labs/5.md
  labs/6.md
Labels: size/M
